weddingInvite/app1/urls.py
from django.urls import path

from app1 import views

app_name = 'guests'

urlpatterns = [
    path('', views.GuestsView.as_view(), name='guest_list'),
    path('personalize/', views.CreatePersonalizedInvitationView.as_view(), name='personalized_invitation'),
    path('<int:pk>/updateinvite/', views.UpdateInviteView.as_view(), name='update_invite'),
    path('finalinvite/', views.FinalInvitationView.as_view(), name='final_invitation'),
    path('modifiedinvite/', views.ListModifiedInvitationView.as_view(), name='modified_invitation'),
    path('add/', views.CreateGuestsView.as_view(), name='add'),
    path('confirmation/', views.CreateConfirmationView.as_view(), name='confirmation_form'),
    path('infirmation/', views.Infirmation.as_view(), name='infirmation_form'),
    path('<int:pk>/update/', views.UpdateGuestsView.as_view(), name='update'),
    path('<int:pk>/delete/', views.delete_location, name='delete'),
    path('<int:pk>/activate/', views.activate_location, name='activate'),
    path('confirmationmessage/', views.confirmation_message, name='confirmation'),
    path('infirmationonmessage/', views.infirmation_message, name='infirmation'),
    path('churchpartylocations/', views.MapsViewUser.as_view(), name='churchpartylocations'),
    path('clientrestaurantlocation/', views.MapsRestaurantViewClient.as_view(), name='clientrestaurantlocation'),
    path('clientchurchlocation/', views.MapsChurchViewClient.as_view(), name='clientchurchlocation'),
    # path('exporttemplate', views.export_template, name='export')
    # path('emailmessage/', views.email_message, name='emailmessage')
]

weddingInvite/weddingInvite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from app1 import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('guests/', include('app1.urls')),
    path('home/', views.HomePage.as_view(), name='home'),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('userprofile/', include('userprofile.urls')),
]

weddingInvite/app1/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class ConfirmationOfPresence(models.Model):
    prenume = models.CharField(max_length=100)
    nume = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    număr_telefon = models.CharField(max_length=30)
    număr_adulți = models.IntegerField(null=True)
    număr_copii = models.IntegerField(null=True)
    confirmare_prezență = models.CharField(
        max_length=3,
        choices=[("DA", "DA"), ("NU", "NU")],
        default="DA"
        )
    active = models.BooleanField(default=True)
    utilizator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.prenume} -> {self.nume}'


class PersonalizedInvitation(models.Model):
    nume_mireasă = models.CharField(max_length=100)
    nume_mire = models.CharField(max_length=100)
    dată_eveniment = models.CharField(max_length=100)
    părinții_miresei = models.CharField(max_length=100)
    părinții_mirelui = models.CharField(max_length=100)
    nume_nașă = models.CharField(max_length=100)
    nume_naș = models.CharField(max_length=100)
    nume_biserică = models.CharField(max_length=100)
    ora_cununie_religioasă = models.CharField(max_length=100)
    local_petrecere = models.CharField(max_length=100)
    ora_petrecere = models.CharField(max_length=100)
    utilizator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nume_mireasă} -> {self.nume_mire}'


class Address(models.Model):
    adresă_local = models.CharField(max_length=100)
    adresă_biserică = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.adresă_local} si {self.adresă_biserică}'

weddingInvite/app1/forms.py
from django import forms

from app1.models import ConfirmationOfPresence


class InfirmationForm(forms.ModelForm):

    class Meta:
        model = ConfirmationOfPresence
        fields = ['prenume', 'nume', 'confirmare_prezență']







        # def clean(self):
        #     cleaned_data = super().clean()
        #     prenume = cleaned_data.get('prenume')
        #     nume = cleaned_data.get('nume')
        #
        #     if ConfirmationOfPresence.objects.filter(prenume=prenume, nume=nume).exists():
        #         raise forms.ValidationError("Combinația de nume există deja.")
        #     return cleaned_data


        # def clean_număr_telefon(self):
        #     val = self.cleaned_data.get('număr_telefon')
        #     if val is None:
        #         return ''
        #     return ''
        # def clean_număr_adulți(self):
        #     val = self.cleaned_data.get('număr_adulți')
        #     if val is None:
        #         return ''
        #     return ''
        # #
        # def clean_număr_copii(self):
        #     val = self.cleaned_data.get('număr_copii')
        #     if val is None:
        #         return ''
        #     return val

weddingInvite/app1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, TemplateView

from app1.forms import InfirmationForm
from app1.models import ConfirmationOfPresence, Address
from app1.models import PersonalizedInvitation
from weddingInvite.settings import API_KEY


# import wkhtmltoimage


class GuestsView(LoginRequiredMixin, ListView):
    model = ConfirmationOfPresence
    template_name = 'app1/guests_index.html'


    def get_queryset(self):
        return ConfirmationOfPresence.objects.filter(utilizator=self.request.user, active=True)


# Creare formular completare date invitati
class CreateGuestsView(LoginRequiredMixin, CreateView):
    model = ConfirmationOfPresence
    fields = ['prenume', 'nume', 'email', 'număr_telefon',
              'număr_adulți', 'număr_copii', 'confirmare_prezență']
    template_name = 'app1/guests_form.html'


    def get_success_url(self):
        return reverse('guests:guest_list')



# Modificare formular date invitati
class UpdateGuestsView(LoginRequiredMixin, UpdateView):
    model = ConfirmationOfPresence
    fields = ['prenume', 'nume', 'email', 'număr_telefon',
              'număr_adulți', 'număr_copii', 'confirmare_prezență']
    template_name = 'app1/guests_form.html'


    def get_success_url(self):
        return reverse('guests:guest_list')



# Creare formular pentru introducerea datelor personalizate in invitatie
class CreatePersonalizedInvitationView(LoginRequiredMixin, CreateView):
    model = PersonalizedInvitation
    fields = ['nume_mireasă', 'nume_mire', 'dată_eveniment', 'părinții_miresei', 'părinții_mirelui',
              'nume_nașă', 'nume_naș', 'nume_biserică', 'ora_cununie_religioasă', 'local_petrecere', 'ora_petrecere']
    template_name = 'app1/invitation_form.html'

    def form_valid(self, form):
        form.instance.utilizator = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('guests:modified_invitation')



# Update date din invitatie
class UpdateInviteView(LoginRequiredMixin, UpdateView):
    model = PersonalizedInvitation
    fields = ['nume_mireasă', 'nume_mire', 'dată_eveniment', 'părinții_miresei', 'părinții_mirelui',
              'nume_nașă', 'nume_naș', 'nume_biserică', 'ora_cununie_religioasă', 'local_petrecere', 'ora_petrecere']
    template_name = 'app1/invitation_form.html'

    def get_success_url(self):
        return reverse('guests:modified_invitation')


# Listare invitatie modificata(parte client)
class ListModifiedInvitationView(LoginRequiredMixin, ListView):
    model = PersonalizedInvitation
    fields = ['nume_mireasă', 'nume_mire', 'dată_eveniment', 'părinții_miresei', 'părinții_mirelui',
              'nume_nașă', 'nume_naș', 'nume_biserică', 'ora_cununie_religioasă', 'local_petrecere', 'ora_petrecere']
    template_name = 'app1/invitation_modified.html'

    def get_queryset(self):
        return PersonalizedInvitation.objects.order_by('-id')[:1]

# Listare invitatie modificata(parte invitat) - aici cred ca pot conditiona ce navbar sa imi apara in functie de link-ul de pe care merg acolo.
class FinalInvitationView(LoginRequiredMixin, ListView):
    model = PersonalizedInvitation
    fields = ['nume_mireasă', 'nume_mire', 'dată_eveniment', 'părinții_miresei', 'părinții_mirelui',
              'nume_nașă', 'nume_naș', 'nume_biserică', 'ora_cununie_religioasă', 'local_petrecere', 'ora_petrecere']
    template_name = 'app1/invitation_final.html'

    def get_queryset(self):
        return PersonalizedInvitation.objects.order_by('-id')[:1]

# Stergere date dabel invitati
@login_required
def delete_location(request, pk):
    ConfirmationOfPresence.objects.filter(id=pk).update(active=False)
    return redirect('guests:guest_list')


# activare - in mod ascuns momentan
@login_required
def activate_location(request, pk):
    ConfirmationOfPresence.objects.filter(id=pk).update(active=True)
    return redirect('guests:guest_list')


# Home Page
class HomePage(TemplateView):
    template_name = 'app1/home.html'


# Mesaj confirmare pt invitat
@login_required
def confirmation_message(request):
    return render(request, 'app1/confirmation_message.html')


# Mesaj infirmare invitat
@login_required
def infirmation_message(request):
    return render(request, 'app1/infirmation_message.html')



# Creare formular confirmare de catre invitat
class CreateConfirmationView(LoginRequiredMixin, CreateView):
    model = ConfirmationOfPresence
    fields = ['prenume', 'nume', 'email', 'număr_telefon',
              'număr_adulți', 'număr_copii', 'confirmare_prezență']
    template_name = 'app1/confirmation_form.html'

    def form_valid(self, form):
        form.instance.utilizator = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        if ConfirmationOfPresence.objects.filter(id=self.object.id).exists():
            user_instance = ConfirmationOfPresence.objects.get(id=self.object.id)
            user_instance.save()
            content = (f'Invitatul: {user_instance.prenume} {user_instance.nume} a confirmat prezența la eveniment. \n'
                       f'O să participe {user_instance.număr_adulți} adulți și {user_instance.număr_copii} copii!')
            msg_html = render_to_string('app1/email_received.html', {'content_email': content})
            email = EmailMultiAlternatives(subject='Confirmare eveniment', from_email=user_instance.email, to=['haiduc.hory@gmail.com'])
            email.attach_alternative(msg_html, 'text/html')
            email.send()
        return reverse('guests:confirmation')


# Completare date infirmare - am facut si fisier forms in care am folosir numai campurile dorite la infirmare
class Infirmation(LoginRequiredMixin, CreateView):
    template_name = 'app1/infirmation_form.html'
    form_class = InfirmationForm

    def form_valid(self, form):
        form.instance.utilizator = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('guests:infirmation')


# Creare formular de salvare adrese aferente localului si Bisericii
class MapsViewUser(LoginRequiredMixin, CreateView):
    model = Address
    fields = ['adresă_local', 'adresă_biserică']
    template_name = 'app1/mapsuser.html'

    def get_success_url(self):
        return reverse('guests:modified_invitation')


# API restaurant
class MapsRestaurantViewClient(LoginRequiredMixin, ListView):
    model = Address
    template_name = 'app1/restaurant_location_api.html'

    def get_queryset(self):
        return Address.objects.order_by('-id')[:1]

    def my_view_restaurant(self, request):
        context = {
            'api_key': API_KEY,
        }
        return render(request, 'app1/restaurant_location_api.html', context)

    def get_success_url(self):
        return reverse('guests:clientrestaurantlocation')


# API Biserica
class MapsChurchViewClient(LoginRequiredMixin, ListView):
    model = Address
    template_name = 'app1/church_location_api.html'

    def get_queryset(self):
        return Address.objects.order_by('-id')[:1]

    def my_view_church(self, request):
        context = {
            'api_key': API_KEY,
        }
        return render(request, 'app1/church_location_api.html', context)

    def get_success_url(self):
        return reverse('guests:clientchurchlocation')









# Aici ar mai fi trebuit un link pentru vizualizare locatie Biserica, dar nu am reusit nici cu cel de restaurant

# @login_required
# def email_message(request):
#     return render(request, 'app1/email_received.html')


# def export_template(request):
#     context = {'key': 'value'}
#     html_content = render_to_string('app1/invitation_final.html', context)
#     # imgkit.from_string(html_content, 'output.png')
#     pdfkit.from_string(html_content, 'output.pdf')
#     return render(request, 'app1/invitation_final.html', context)

weddingInvite/templates/app1/church_location_api.html
<!DOCTYPE html>
<html>
  <head>
    <title>Locație Biserică</title>
    <!-- The callback parameter is required, so we use console.debug as a noop -->
    <script async src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&callback=console.debug&libraries=maps,marker&v=beta">
    </script>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      gmp-map {
        height: 100%;
      }

      /* Optional: Makes the sample page fill the window. */
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
{% for coordinates in address_list %}
      <gmp-map center="{{ coordinates.adresă_biserică }}" zoom="15" map-id="DEMO_MAP_ID">
      <gmp-advanced-marker position="{{ coordinates.adresă_biserică }}" title="LOCAȚIA BISERICII - TE AȘTEPTĂM !!!"></gmp-advanced-marker>
      </gmp-map>
{% endfor %}
  </body>
</html>

weddingInvite/templates/app1/confirmation_message.html
{% extends 'base.html' %}
{% block invisible_all_other_pages %}
{% endblock %}
{% block invisible_invitation_final %}
{% endblock %}
{% load static %}
{% block title %}

<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'invitation_form.css' %}" type="text/css" >
</head>

<body>
    <div class="container-general">
      <div class="container-form">
            <div class="card-form">
                <div class="form-group-container">
                    <strong><h6>Îți mulțumim pentru confirmare!</h6></strong>
                    <strong><h6>Te așteptăm pe ringul de dans!</h6></strong>
                    <strong><h3>🕺</h3></strong>
                    <p>Vei fi redirecționat în 5 secunde către Home!</p>
                </div>
            </div>
        </div>
    </div>

    <script>
        setTimeout(function() {
            window.location.href = "{% url 'guests:final_invitation' %}";
        }, 5000);
    </script>

</body>
{% endblock %}

weddingInvite/templates/app1/email_received.html
{{ content_email }}

weddingInvite/templates/app1/guests_form.html
{% extends 'base.html' %}
{% load static %}

{% block invisible_invitation_final %}
{% endblock %}

{% block invisible_all_other_pages %}
{% endblock %}




{% block title %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'invitation_form.css' %}" type="text/css" >
</head>

    <body>
  <div class="container-form">
        <div class="card-form">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group-container">
                        <p class="field-name">{{ field.label }}:</p>
                        {{ field }}
                        <span class="text-danger small">{{ field.errors }}</span>
                    </div>
                {% endfor %}

                {% if 'guests' in request.path and 'update' in request.path %}
                    <a class="btn-forward" href="{% url 'guests:guest_list' %}">Înapoi</a>
                        <button class="btn-forward">Salvează raspunsul</button>

                {% elif request.path == 'guests/confirmation' or request.path == 'guests/infirmation' %}
                    <a class="btn-forward" href="{% url 'guests:final_invitation' %}">Înapoi</a>
                    <button class="btn-forward">Salvează raspunsul</button>
                {% endif %}
            </form>
        </div>
    </div>
</body>
{% endblock %}

weddingInvite/templates/app1/guests_index.html
{% extends 'base.html' %}
{% load static %}
{% block invisible_all_other_pages %}
{% endblock %}
{% block title %}

<head>
<!--    <link rel="stylesheet" href="{% static 'guests.css' %}" type="text/css" >-->
    <style>
        .btn-warning, .btn-danger, .btn-info {
            margin-top: 0px;
            margin-left: 30px;
}
        .container-table {
            margin: 30px 25px 0 25px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        td, th {
            margin: 0;
        }

        .final-column {
            width: 12%;
        }

    </style>
</head>

<body>
    <div class="container-table">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Index</th>
                    <th>Prenume</th>
                    <th>Nume</th>
                    <th>Email</th>
                    <th>Număr telefon</th>
                    <th>Număr adulți</th>
                    <th>Număr copii</th>
                    <th>Vin(DA/NU)</th>
                    <th class="final-column">Acțiuni</th>
                </tr>
            </thead>

            <tbody>
                {% for item in confirmationofpresence_list %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ item.prenume }} </td>
                        <td> {{ item.nume }} </td>
                        <td> {{ item.email }}</td>
                        <td> {{ item.număr_telefon }}</td>
                        <td> {{ item.număr_adulți }}</td>
                        <td> {{ item.număr_copii }}</td>
                        <td> {{ item.confirmare_prezență }}</td>
                        <td class="final-column">
                            <a class="btn btn-sm btn-warning" href="{% url 'guests:update' item.id %}">Editează</a>
                            <a class="btn btn-sm btn-danger" href="{% url 'guests:delete' item.id %}">Șterge</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
{% endblock %}










<!--                    <td> {{ item.active }}</td>-->
<!--                        <a class="btn btn-sm btn-info" href="{% url 'guests:activate' item.id %}">Activate</a>-->

weddingInvite/templates/app1/home.html
{% extends 'base.html' %}
{% block invisible_all_other_pages %}
{% endblock %}
{% load static %}
{% block title %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home.css' %}" type="text/css" >
    <style>
        h1, h2, p {
            font-family: 'Great Vibes', cursive;;
            color: black;
            }
    </style>
</head>

<body>
    <div class="invitation-container">
            <div class="invitation">
                <h1>Cu inimile pline de emoție și bucurie, noi</h1>
                <h2>Mireasă & Mire</h2>
                <p>Vă invităm să fiți alături de noi la celebrarea căsătoriei noastre.</p>
                <div class="event-date">
                    <p>Data Evenimentului:</p>
                    <p><strong>29 mai 2025</strong></p>
                </div>
                <div class="parents">
                    <p>Alături ne vor fi părinții:</p>
                    <p><strong>Părinți mireasă</strong> & <strong>Părinți mire</strong></p>
                </div>
                <div class="godfather-godmother">
                    <p>Și nașii:</p>
                    <p><strong>Nașa</strong> & <strong>Nașul</strong></p>
                </div>
                <div class="church">
                    <p>Ne vom cununa religios la:</p>
                    <p><strong>Biserica "numele Bisericii"</strong> la ora <strong>12:00</strong></p>
                </div>
                <div class="party">
                    <p>Vom petrece împreună la <strong>"Nume local"</strong> la ora <strong>14:00</strong></p>
                    <p>Vă așteptăm cu drag!</p>
                </div>
            </div>
        <div id="modify-invitation-button" class="position-absolute bottom-0 start-50 translate-middle-x">
            {% if request.user.is_authenticated %}
                <a class="btn btn-outline-dark" href="{% url 'guests:personalized_invitation' %}">Customizează</a>
            {% else %}
                <a class="btn btn-outline-dark" href="{% url 'login' %}">Customizează</a>
            {% endif %}
        </div>
    </div>
</body>

{% endblock %}

weddingInvite/templates/app1/infirmation_form.html
{% extends 'base.html' %}
{% load static %}
{% block invisible_invitation_final %}
{% endblock %}

{% block title %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'invitation_form.css' %}" type="text/css" >
</head>

    <body>
  <div class="container-form">
        <div class="card-form">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group-container">
                        <p class="field-name">{{ field.label }}:</p>
                        {{ field }}
                        <span class="text-danger small">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <a class="btn-forward" href="{% url 'guests:final_invitation' %}">Înapoi</a>
                <button class="btn-forward">Salvează raspunsul</button>
            </form>
        </div>
    </div>
</body>
{% endblock %}

weddingInvite/templates/app1/infirmation_message.html
{% extends 'base.html' %}
{% block invisible_all_other_pages %}
{% endblock %}
{% block invisible_invitation_final %}
{% endblock %}
{% load static %}
{% block title %}

<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'invitation_form.css' %}" type="text/css" >
</head>

<body>
    <div class="container-general">
      <div class="container-form">
            <div class="card-form">
                <div class="form-group-container">
                    <strong><h6>Îți mulțumim pentru răspuns!</h6></strong>
                    <p>Vei fi redirecționat în 5 secunde către "Acasă"!</p>
                </div>
            </div>
        </div>
    </div>

    <script>
        setTimeout(function() {
            window.location.href = "{% url 'guests:final_invitation' %}";
        }, 5000);
    </script>

</body>
{% endblock %}

weddingInvite/templates/app1/invitation_final.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% block invisible_invitation_final %}
{% endblock %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home.css' %}" type="text/css" >
    <style>
        h1, h2, p {
            font-family: 'Great Vibes', cursive;;
            color: black;
            }
    </style>
</head>

<body>
    <div class="invitation-container">
        {% for item in personalizedinvitation_list %}
            <div class="invitation">
                <h1>Cu inimile pline de emoție și bucurie, noi</h1>
                <h2> {{ item.nume_mireasă }} & {{ item.nume_mire }} </h2>
                <p>Vă invităm să fiți alături de noi la celebrarea căsătoriei noastre.</p>
                <div class="event-date">
                    <p>Data Evenimentului:</p>
                    <p><strong> {{ item.dată_eveniment }} </strong></p>
                </div>
                <div class="parents">
                    <p>Alături ne vor fi părinții:</p>
                    <p><strong> {{ item.părinții_miresei }}</strong> & <strong>{{ item.părinții_mirelui }} </strong></p>
                </div>
                <div class="godfather-godmother">
                    <p>Și nașii:</p>
                    <p><strong>{{ item.nume_nașă }}</strong> & <strong>{{ item.nume_naș }}</strong></p>
                </div>
                <div class="church">
                    <p>Ne vom cununa religios la:</p>
                    <p>Biserica <strong>"{{ item.nume_biserică }}"</strong></strong> la ora <strong>{{ item.ora_cununie_religioasă }}</strong></p>
                </div>
                <div class="party">
                    <p>Vom petrece împreună la <strong>{{ item.local_petrecere }}</strong> la ora <strong>{{ item.ora_petrecere }}</strong></p>
                    <p>Vă așteptăm cu drag!</p>
                </div>
            </div>
        {% endfor %}

    </div>
</body>
{% endblock %}

weddingInvite/templates/app1/invitation_modified.html
{% extends 'base.html' %}
{% block invisible_all_other_pages %}
{% endblock %}
{% load static %}
{% block title %}
<head>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home.css' %}" type="text/css" >
    <style>
        h1, h2, p {
            font-family: 'Great Vibes', cursive;;
            color: black;
            }
    </style>
</head>

<body>
    <div class="invitation-container">
        {% for item in personalizedinvitation_list %}
            {{ forloop.counter }}
            <div class="invitation">
                <h1>Cu inimile pline de emoție și bucurie, noi</h1>
                <h2> {{ item.nume_mireasă }} & {{ item.nume_mire }} </h2>
                <p>Vă invităm să fiți alături de noi la celebrarea căsătoriei noastre.</p>
                <div class="event-date">
                    <p>Data Evenimentului:</p>
                    <p><strong> {{ item.dată_eveniment }} </strong></p>
                </div>
                <div class="parents">
                    <p>Alături ne vor fi părinții:</p>
                    <p><strong> {{ item.părinții_miresei }}</strong> & <strong>{{ item.părinții_mirelui }} </strong></p>
                </div>
                <div class="godfather-godmother">
                    <p>Și nașii:</p>
                    <p><strong>{{ item.nume_nașă }}</strong> & <strong>{{ item.nume_naș }}</strong></p>
                </div>
                <div class="church">
                    <p>Ne vom cununa religios la:</p>
                    <p>Biserica <strong>"{{ item.nume_biserică }}"</strong></strong> la ora <strong>{{ item.ora_cununie_religioasă }}</strong></p>
                </div>
                <div class="party">
                    <p>Vom petrece împreună la <strong>"{{ item.local_petrecere }}"</strong> la ora <strong>{{ item.ora_petrecere }}</strong></p>
                    <p>Vă așteptăm cu drag!</p>
                </div>
            </div>

        <div id="modify-invitation-button" class="position-absolute bottom-0 start-50 translate-middle-x">
            <a class="btn btn-outline-dark" href="{% url 'guests:update_invite' item.id %}">Editare</a>
            <a class="btn btn-outline-dark" href="{% url 'guests:final_invitation' %}">Finalizează</a>

        </div>
        {% endfor %}
    </div>
</body>
{% endblock %}