weddingInvite/app1/urls.py
from django.urls import path

from app1 import views

app_name = 'guests'

urlpatterns = [
    path('', views.GuestsView.as_view(), name='guest_list'),
    path('personalize/', views.CreatePersonalizedInvitationView.as_view(), name='personalized_invitation'),
    path('<int:pk>/updateinvite/', views.UpdateInviteView.as_view(), name='update_invite'),
    path('finalinvite/', views.FinalInvitationView.as_view(), name='final_invitation'),
    path('modifiedinvite/', views.ListModifiedInvitationView.as_view(), name='modified_invitation'),
    path('add/', views.CreateGuestsView.as_view(), name='add'),
    path('confirmation/', views.CreateConfirmationView.as_view(), name='confirmation_form'),
    path('infirmation/', views.Infirmation.as_view(), name='infirmation_form'),
    path('<int:pk>/update/', views.UpdateGuestsView.as_view(), name='update'),
    path('<int:pk>/delete/', views.delete_location, name='delete'),
    path('<int:pk>/activate/', views.activate_location, name='activate'),
    path('confirmationmessage/', views.confirmation_message, name='confirmation'),
    path('infirmationonmessage/', views.infirmation_message, name='infirmation'),
    path('churchpartylocations/', views.MapsViewUser.as_view(), name='churchpartylocations'),
    path('clientrestaurantlocation/', views.MapsRestaurantViewClient.as_view(), name='clientrestaurantlocation'),
    path('clientchurchlocation/', views.MapsChurchViewClient.as_view(), name='clientchurchlocation'),
    # path('exporttemplate', views.export_template, name='export')
    # path('emailmessage/', views.email_message, name='emailmessage')
]

weddingInvite/userprofile/urls.py
from django.urls import path
from userprofile import views


app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='new_user')
]

weddingInvite/weddingInvite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from app1 import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('guests/', include('app1.urls')),
    path('home/', views.HomePage.as_view(), name='home'),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('userprofile/', include('userprofile.urls')),
]

weddingInvite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css" >

        <style>
            @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
            html, body, {
/*                position: fixed;*/
                top: 0;
                left: 0;
                bottom: 0;
                right: 0;
            }

            .btn {

                margin-left: 15px;
                margin-top: 15px;
                padding: 4px;
            }
        </style>

    </head>

{% block invisible_invitation_final %}
    <body>
        {% if request.user.is_authenticated %}
            <nav>
                <div class="d-flex justify-content-start">
                        <a class="btn btn-outline-light" href="{% url 'guests:guest_list' %}">Invitați</a>
                    {% if request.user.is_superuser %}
                        <a class="btn btn-outline-light" href="/admin">Admin</a>
                    {% endif %}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-outline-light" type="submit">Deconectare</button>
                    </form>
                    <a class="btn btn-outline-light" href="{% url 'userprofile:new_user' %}">Cont nou</a>
                    {% if request.path != 'home' %}
                        <a class="btn btn-outline-light" href="{% url 'home' %}">Acasă</a>
                    {% endif %}

                    {% if request.path == '/guests/modifiedinvite/' %}
                    <a class="btn btn-outline-light" href="{% url 'guests:churchpartylocations' %}">Introdu coordonate</a>
                    <a class="btn btn-outline-light" target="blank" href="https://www.google.com/maps/@46.7826949,23.6178987,14z?entry=ttu">Caută coordonate</a>
                    {% endif %}
                </div>
            </nav>
        {% endif %}
    </body>
{% endblock %}

{% block invisible_all_other_pages %}
    <div class="d-flex justify-content-start">
        {% if request.user.is_superuser %}
            <a class="btn btn-outline-light" href="{% url 'home' %}">Acasă</a>
        {% endif %}
        <a class="btn btn-outline-light" href="{% url 'guests:confirmation_form' %}">Particip</a>
        <a class="btn btn-outline-light" href="{% url 'guests:infirmation_form' %}">Nu particip</a>
        <a class="btn btn-outline-light" target="blank" href="{% url 'guests:clientchurchlocation' %}">Locație Biserică</a>
        <a class="btn btn-outline-light" target="blank" href="{% url 'guests:clientrestaurantlocation' %}">Locație Restaurant</a>
    </div>
{% endblock %}

{% block title %} {% endblock %}
</html>